version: '3.3'
services:
  server_dev:
    container_name: Dashboard_server-dev
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      PORT: 80
      GIN_MODE: debug
    ports:
      - 8080:80
    restart: on-failure
    volumes:
      - api_dev:/api_dev
      - dashboard_db_dev:/database_dev
    networks:
      - dashboard-network
  front_dev:
    container_name: dashboard_front-dev
    build:
      context: front
      dockerfile: Dockerfile
    depends_on:
      - server_dev
    volumes:
      - app_dev:/app_dev
      - app_dev_node_modules:/app_dev/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - dashboard-network

volumes:
  api_dev:
  dashboard_db_dev:
  app_dev:
  app_dev_node_modules:

networks:
  dashboard-network:
    driver: bridge
