version: '3.3'
services:
  server_dev:
    container_name: Dashboard-api
    build: .
    environment:
      PORT: 8080
      # GIN_MODE: release
      GIN_MODE: debug
    expose:
      - 8080
    #    ports:
    #      - 8080:8080
    restart: on-failure
    volumes:
      - api_dev:/usr/src/api_dev/
#    depends_on:
#      - fullstack-postgres
#    networks:
#      - fullstack

volumes:
  api_dev:
#  database_postgres:

# Networks to be created to facilitate communication between containers
#networks:
#  fullstack:
#    driver: bridge
