version: '3.3'
services:
  server_dev:
    container_name: Dashboard-api_dev
    build: .
    environment:
      PORT: 6666
      # GIN_MODE: release
      GIN_MODE: debug
    ports:
      - 8080:6666
    restart: on-failure
    volumes:
      - api_dev:/usr/src/api_dev/
      - sqlite:/database

#    depends_on:
#      - fullstack-postgres
#    networks:
#      - fullstack

volumes:
  api_dev:
  sqlite:
#  database_postgres:

# Networks to be created to facilitate communication between containers
#networks:
#  fullstack:
#    driver: bridge
